#!/bin/bash

current_branch=$(git rev-parse --abbrev-ref HEAD)
if [[ $current_branch == 'master' ]]; then
    webpack
    cp east_boston.js ../utility
    eval 'cd ../utility && git add east_boston.js && git commit -m "updated east_boston.js"'
fi
