#!/bin/bash

current_branch=$(git rev-parse --abbrev-ref HEAD)
if [[ $current_branch == 'master' ]]; then
    webpack
    cp east_boston.js ../utility/
    cd ../utility && git add . && git commit -am "updated east_boston.js" && git push origin master
fi
