#!/bin/bash

. git-sh-setup  # for require_clean_work_tree() and die()

check_push_to_master()
{
    # we're pushing to remote "master"; reject if
    # the work tree is not clean or is not at the
    # commit-ID ($1) being pushed
    local headsha pushsha

    require_clean_work_tree 'push to master'
    headsha=$(git rev-parse HEAD)
    pushsha=$1
    [ $headsha = $pushsha ] ||
        die "HEAD commit $headsha does not match push to master $pushsha"
}

to_master=false
while read lref lsha rref rsha; do
    case $rref in
    refs/heads/master) check_push_to_master $lsha; to_master=true;;
    esac
done

if $to_master; then
    unset GIT_DIR
    npm run-script build
    cp maps.js ../utility
    cd ../utility && git pull && git add east_boston.js maps.js && git commit -m "updated maps.js" && git push origin master
fi
exit 0 # allow push to proceed
